{% set name = "dlpack" %}
{% set version = "0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dmlc/dlpack/archive/v{{ version }}.tar.gz
  sha256: cf965c26a5430ba4cc53d61963f288edddcd77443aa4c85ce722aaf1e2f29513

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make

test:
  commands:
    - test -d ${PREFIX}/include/dlpack  # [unix]
    - test -f ${PREFIX}/include/dlpack/dlpack.h  # [unix]
    - test -d ${PREFIX}/lib/cmake/dlpack  # [unix]

about:
  home: https://github.com/dmlc/dlpack
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: DLPack - Open In Memory Tensor Structure
  description: |
    DLPack is an open in-memory tensor structure to for sharing tensor among frameworks
  dev_url: https://github.com/dmlc/dlpack

extra:
  recipe-maintainers:
    - marcelotrevisani
    - kkraus14
    - jakirkham
